export const SHOW_CREATE_PLAYLIST_MODAL = 'SHOW_CREATE_PLAYLIST_MODAL';
export const HIDE_CREATE_PLAYLIST_MODAL = 'HIDE_CREATE_PLAYLIST_MODAL';

export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const REORDER_PLAYLIST = 'REORDER_PLAYLIST';
export const REORDER_PLAYLISTS = 'REORDER_PLAYLISTS';

export const CLICK_PLAYLIST_TITLE = 'CLICK_PLAYLIST_TITLE';
export const CHANGE_PLAYLIST_TITLE = 'CHANGE_PLAYLIST_TITLE';

export const SHOW_CREATE_RESOURCE_MODAL = 'SHOW_CREATE_RESOURCE_MODAL';
export const HIDE_CREATE_RESOURCE_MODAL = 'HIDE_CREATE_RESOURCE_MODAL';

export const SHOW_RESOURCE_SELECT_ACTIVITY = 'SHOW_RESOURCE_SELECT_ACTIVITY';
export const SHOW_RESOURCE_ACTIVITY_TYPE = 'SHOW_RESOURCE_ACTIVITY_TYPE';

export const SHOW_RESOURCE_ACTIVITY_BUILD = 'SHOW_RESOURCE_ACTIVITY_BUILD';
export const HIDE_RESOURCE_ACTIVITY_BUILD = 'HIDE_RESOURCE_ACTIVITY_BUILD';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const LOAD_RESOURCE = 'LOAD_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';

export const PREVIEW_RESOURCE = 'PREVIEW_RESOURCE';

export const HIDE_PREVIEW_PLAYLIST_MODAL = 'HIDE_PREVIEW_PLAYLIST_MODAL';

export const SHOW_CREATE_PROJECT_MODAL = 'SHOW_CREATE_PROJECT_MODAL';
export const HIDE_CREATE_PROJECT_MODAL = 'HIDE_CREATE_PROJECT_MODAL';

export const SHOW_CREATE_PROJECT_SUBMENU = 'SHOW_CREATE_PROJECT_SUBMENU';

export const SHOW_USER_SUB_MENU = 'SHOW_USER_SUB_MENU';

export const CLOSE_MENU = 'CLOSE_MENU';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SHARE_PROJECT = 'SHARE_PROJECT';

export const LOAD_MY_PROJECTS = 'LOAD_MY_PROJECTS';

export const LOAD_PLAYLIST = 'LOAD_PLAYLIST';

export const LOAD_PROJECT_PLAYLISTS = 'LOAD_PROJECT_PLAYLISTS';

export const SHOW_DELETE_POPUP = 'SHOW_DELETE_POPUP';
export const HIDE_DELETE_POPUP = 'HIDE_DELETE_POPUP';

export const SHOW_DELETE_PROJECT_MODAL = 'SHOW_DELETE_PROJECT_MODAL';

export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADING_COMPLETE = 'PAGE_LOADING_COMPLETE';

export const PROJECT_THUMBNAIL_PROGRESS = 'PROJECT_THUMBNAIL_PROGRESS';
export const UPLOAD_PROJECT_THUMBNAIL = 'UPLOAD_PROJECT_THUMBNAIL';

export const RESOURCE_THUMBNAIL_PROGRESS = 'RESOURCE_THUMBNAIL_PROGRESS';
export const UPLOAD_RESOURCE_THUMBNAIL = 'UPLOAD_RESOURCE_THUMBNAIL';

export const SHOW_RESOURCE_DESCRIBE_ACTIVITY = 'SHOW_RESOURCE_DESCRIBE_ACTIVITY';

export const SELECT_ACTIVITY = 'SELECT_ACTIVITY';
export const SELECT_ACTIVITY_TYPE = 'SELECT_ACTIVITY_TYPE';
export const DESCRIBE_ACTIVITY = 'DESCRIBE_ACTIVITY';

export const RESOURCE_VALIDATION_ERRORS = 'RESOURCE_VALIDATION_ERRORS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const LOG_OUT = 'LOG_OUT';

export const LOAD_H5P = 'LOAD_H5P';
export const SHOW_LMS = 'SHOW_LMS';
export const LOAD_MY_PROJECTS_SELECTED = 'LOAD_MY_PROJECTS_SELECTED';
export const CHANGE_LOADING = 'CHANGE_LOADING';

export const SAVE_GENERIC_RESOURCE = 'SAVE_GENERIC_RESOURCE';
