export const SHOW_CREATE_PLAYLIST_MODAL = 'SHOW_CREATE_PLAYLIST_MODAL';
export const HIDE_CREATE_PLAYLIST_MODAL = 'HIDE_CREATE_PLAYLIST_MODAL';

export const REORDER_PLAYLIST = 'REORDER_PLAYLIST';

export const SHOW_CREATE_RESOURCE_MODAL = 'SHOW_CREATE_RESOURCE_MODAL';
export const HIDE_CREATE_RESOURCE_MODAL = 'HIDE_CREATE_RESOURCE_MODAL';

export const SHOW_RESOURCE_SELECT_ACTIVITY = 'SHOW_RESOURCE_SELECT_ACTIVITY';
export const SHOW_RESOURCE_ACTIVITY_TYPE = 'SHOW_RESOURCE_ACTIVITY_TYPE';

export const SHOW_RESOURCE_ACTIVITY_BUILD = 'SHOW_RESOURCE_ACTIVITY_BUILD';
export const HIDE_RESOURCE_ACTIVITY_BUILD = 'HIDE_RESOURCE_ACTIVITY_BUILD';

export const PREVIEW_RESOURCE = 'PREVIEW_RESOURCE';

export const HIDE_PREVIEW_PLAYLIST_MODAL = 'HIDE_PREVIEW_PLAYLIST_MODAL';

export const SHOW_CREATE_PROJECT_MODAL = 'SHOW_CREATE_PROJECT_MODAL';
export const HIDE_CREATE_PROJECT_MODAL = 'HIDE_CREATE_PROJECT_MODAL';

export const LOAD_PLAYLIST = 'LOAD_PLAYLIST';

export const SHOW_DELETE_POPUP = 'SHOW_DELETE_POPUP';
export const HIDE_DELETE_POPUP = 'HIDE_DELETE_POPUP';

export const SHOW_DELETE_PROJECT_MODAL = 'SHOW_DELETE_PROJECT_MODAL';

export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADING_COMPLETE = 'PAGE_LOADING_COMPLETE';

export const PROJECT_THUMBNAIL_PROGRESS = 'PROJECT_THUMBNAIL_PROGRESS';
export const UPLOAD_PROJECT_THUMBNAIL = 'UPLOAD_PROJECT_THUMBNAIL';

export const RESOURCE_THUMBNAIL_PROGRESS = 'RESOURCE_THUMBNAIL_PROGRESS';
export const UPLOAD_RESOURCE_THUMBNAIL = 'UPLOAD_RESOURCE_THUMBNAIL';

export const SHOW_RESOURCE_DESCRIBE_ACTIVITY = 'SHOW_RESOURCE_DESCRIBE_ACTIVITY';

export const SELECT_ACTIVITY = 'SELECT_ACTIVITY';
export const SELECT_ACTIVITY_TYPE = 'SELECT_ACTIVITY_TYPE';
export const DESCRIBE_ACTIVITY = 'DESCRIBE_ACTIVITY';

export const RESOURCE_VALIDATION_ERRORS = 'RESOURCE_VALIDATION_ERRORS';

export const LOAD_H5P = 'LOAD_H5P';
export const SHOW_LMS = 'SHOW_LMS';
export const CHANGE_LOADING = 'CHANGE_LOADING';

export const GOOGLE_CLASSROOM_LOGIN = 'GOOGLE_CLASSROOM_LOGIN';
export const SAVE_GENERIC_RESOURCE = 'SAVE_GENERIC_RESOURCE';
export const GOOGLE_SHARE = 'GOOGLE_SHARE';
export const GOOGLE_CLASSROOM_LOGIN_FAILURE = 'GOOGLE_CLASSROOM_LOGIN_FAILURE';

/* New Action Types */

/* Auth & User */
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const CONFIRM_EMAIL_REQUEST = 'CONFIRM_EMAIL_REQUEST';
export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS';
export const CONFIRM_EMAIL_FAIL = 'CONFIRM_EMAIL_FAIL';

export const ACCEPT_TERMS_REQUEST = 'ACCEPT_TERMS_REQUEST';
export const ACCEPT_TERMS_SUCCESS = 'ACCEPT_TERMS_SUCCESS';
export const ACCEPT_TERMS_FAIL = 'ACCEPT_TERMS_FAIL';

export const LOG_OUT = 'LOG_OUT';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';

export const LOAD_ORGANIZATION_TYPES = 'LOAD_ORGANIZATION_TYPES';
/* Auth & User */

/* Project */
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';

export const LOAD_PROJECT_REQUEST = 'LOAD_PROJECT_REQUEST';
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS';
export const LOAD_PROJECT_FAIL = 'LOAD_PROJECT_FAIL';
export const LOAD_MY_CLONE_PROJECTS = 'LOAD_MY_CLONE_PROJECTS';

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

export const LOAD_MY_PROJECTS = 'LOAD_MY_PROJECTS';
export const LOAD_MY_PROJECTS_SELECTED = 'LOAD_MY_PROJECTS_SELECTED';
export const SHARE_PROJECT = 'SHARE_PROJECT';

export const SIDEBAR_ALL_PROJECT = 'SIDEBAR_ALL_PROJECT';
export const SIDEBAR_SAMPLE_PROJECT = 'SIDEBAR_SAMPLE_PROJECT';
export const SIDEBAR_UPDATE_PROJECT = 'SIDEBAR_UPDATE_PROJECT';
/* Project */

/* Playlist */
export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAIL = 'CREATE_PLAYLIST_FAIL';

export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST';
export const LOAD_PLAYLIST_SUCCESS = 'LOAD_PLAYLIST_SUCCESS';
export const LOAD_PLAYLIST_FAIL = 'LOAD_PLAYLIST_FAIL';

export const UPDATE_PLAYLIST_REQUEST = 'UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_FAIL = 'UPDATE_PLAYLIST_FAIL';

export const DELETE_PLAYLIST_REQUEST = 'DELETE_PLAYLIST_REQUEST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAIL = 'DELETE_PLAYLIST_FAIL';

export const LOAD_PROJECT_PLAYLISTS = 'LOAD_PROJECT_PLAYLISTS';

export const REORDER_PLAYLISTS_REQUEST = 'REORDER_PLAYLISTS_REQUEST';
export const REORDER_PLAYLISTS_SUCCESS = 'REORDER_PLAYLISTS_SUCCESS';
export const REORDER_PLAYLISTS_FAIL = 'REORDER_PLAYLISTS_FAIL';
/* Playlist */

/* Activity */
export const LOAD_RESOURCE_REQUEST = 'LOAD_RESOURCE_REQUEST';
export const LOAD_RESOURCE_SUCCESS = 'LOAD_RESOURCE_SUCCESS';
export const LOAD_RESOURCE_FAIL = 'LOAD_RESOURCE_FAIL';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const EDIT_RESOURCE = 'EDIT_RESOURCE';

export const RESOURCE_SAVED = 'RESOURCE_SAVED';

export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_FAIL = 'DELETE_RESOURCE_FAIL';

export const LOAD_RESOURCE_TYPES_REQUEST = 'LOAD_RESOURCE_TYPES_REQUEST';
export const LOAD_RESOURCE_TYPES_SUCCESS = 'LOAD_RESOURCE_TYPES_SUCCESS';
export const LOAD_RESOURCE_TYPES_FAIL = 'LOAD_RESOURCE_TYPES_FAIL';

export const LOAD_RESOURCE_ITEMS_REQUEST = 'LOAD_RESOURCE_ITEMS_REQUEST';
export const LOAD_RESOURCE_ITEMS_SUCCESS = 'LOAD_RESOURCE_ITEMS_SUCCESS';
export const LOAD_RESOURCE_ITEMS_FAIL = 'LOAD_RESOURCE_ITEMS_FAIL';

export const SAVE_SEARCH_KEY_IN_CREATION = 'SAVE_SEARCH_KEY_IN_CREATION';
export const SAVE_FORM_DATA_IN_CREATION = 'SAVE_FORM_DATA_IN_CREATION';
/* Activity */

export const SET_LMS_COURSE = 'SET_LMS_COURSE';

export const SEARCH_REDUX = 'SEARCH_REDUX';
/* Metrics */

export const GET_USER_METRICS = 'GET_USER_METRICS';
export const GET_USER_MEMBERSHIP = 'GET_USER_MEMBERSHIP';
export const ACTIVITY_VIEWED = 'ACTIVITY_VIEWED';
export const PLAYLIST_VIEWED = 'PLAYLIST_VIEWED';
export const PROJECT_VIEWED = 'PROJECT_VIEWED';
/* Google Share */

export const LOAD_GOOGLE_CLASSROOM_COURSES = 'LOAD_GOOGLE_CLASSROOM_COURSES';
export const ALL_COURSES = 'ALL_COURSES';
export const GET_STUDENT_COURSES = 'GET_STUDENT_COURSES';

/* Team */
export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAIL = 'CREATE_TEAM_FAIL';

export const LOAD_TEAM_REQUEST = 'LOAD_TEAM_REQUEST';
export const LOAD_TEAM_SUCCESS = 'LOAD_TEAM_SUCCESS';
export const LOAD_TEAM_FAIL = 'LOAD_TEAM_FAIL';

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL';

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';

export const LOAD_TEAMS = 'LOAD_TEAMS';

export const RESET_SELECTED_TEAM = 'RESET_SELECTED_TEAM';
export const UPDATE_SELECTED_TEAM = 'UPDATE_SELECTED_TEAM';
export const SHOW_CREATE_TEAM = 'SHOW_CREATE_TEAM';
export const SHOW_INVITE_MEMBER = 'SHOW_INVITE_MEMBER';
export const SHOW_ASSIGN_TEAM = 'SHOW_ASSIGN_TEAM';

export const INVITE_MEMBER_CONFIRM_REQUEST = 'INVITE_MEMBER_CONFIRM_REQUEST';
export const INVITE_MEMBER_CONFIRM_SUCCESS = 'INVITE_MEMBER_CONFIRM_SUCCESS';
export const INVITE_MEMBER_CONFIRM_FAIL = 'INVITE_MEMBER_CONFIRM_FAIL';

export const INVITE_MEMBERS_REQUEST = 'INVITE_MEMBERS_REQUEST';
export const INVITE_MEMBERS_SUCCESS = 'INVITE_MEMBERS_SUCCESS';
export const INVITE_MEMBERS_FAIL = 'INVITE_MEMBERS_FAIL';

export const REMOVE_MEMBER_REQUEST = 'REMOVE_MEMBER_REQUEST';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';
export const REMOVE_MEMBER_FAIL = 'REMOVE_MEMBER_FAIL';

export const ADD_TEAM_PROJECTS_REQUEST = 'ADD_TEAM_PROJECTS_REQUEST';
export const ADD_TEAM_PROJECTS_SUCCESS = 'ADD_TEAM_PROJECTS_SUCCESS';
export const ADD_TEAM_PROJECTS_FAIL = 'ADD_TEAM_PROJECTS_FAIL';

export const REMOVE_PROJECT_REQUEST = 'REMOVE_PROJECT_REQUEST';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';
export const REMOVE_PROJECT_FAIL = 'REMOVE_PROJECT_FAIL';

export const ADD_MEMBERS_TO_PROJECT_REQUEST = 'ADD_MEMBERS_TO_PROJECT_REQUEST';
export const ADD_MEMBERS_TO_PROJECT_SUCCESS = 'ADD_MEMBERS_TO_PROJECT_SUCCESS';
export const ADD_MEMBERS_TO_PROJECT_FAIL = 'ADD_MEMBERS_TO_PROJECT_FAIL';

export const REMOVE_MEMBER_FROM_PROJECT_REQUEST = 'REMOVE_MEMBER_FROM_PROJECT_REQUEST';
export const REMOVE_MEMBER_FROM_PROJECT_SUCCESS = 'REMOVE_MEMBER_FROM_PROJECT_SUCCESS';
export const REMOVE_MEMBER_FROM_PROJECT_FAIL = 'REMOVE_MEMBER_FROM_PROJECT_FAIL';
/* Team */

/* Account */

export const GET_USER_LMS_SETTINGS = 'GET_USER_LMS_SETTINGS';

/* Dashboard */

export const GET_USER_PROJECTS = 'GET_USER_PROJECTS';
export const GET_SHARED_USER_PROJECTS = 'GET_SHARED_USER_PROJECTS';
export const GET_USER_ACTIVITIES = 'GET_USER_ACTIVITIES';
export const GET_SHARED_USER_ACTIVITIES = 'GET_SHARED_USER_ACTIVITIES';
export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';

/* NOTIFICATIONS */

export const ADD_ALL_NOTIFICATIONS = 'ADD_ALL_NOTIFICATIONS';
export const ADD_SINGLE_NOTIFICATION = 'ADD_SINGLE_NOTIFICATION';
export const CLEAR_ALL_NOTIFICATION = 'CLEAR_ALL_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
