const h5pLibraries = [
  {
    text: 'Interactive Video',
    h5pLib: 'H5P.InteractiveVideo 1.21',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/interactive-video.png',
    overlayIcon: '/assets.images/h5p-icons/interactive-video.png',
    description: 'Create videos enriched with interactions',
  },
  {
    text: 'Flash Cards',
    h5pLib: 'H5P.Flashcards 1.5',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/flash-cards.png',
    overlayIcon: '/assets.images/h5p-icons/flash-cards.png',
    description: 'Create stylish and modern flash cards',
  },
  {
    text: 'Drag and Drop',
    h5pLib: 'H5P.DragQuestion 1.13',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/drag-and-drop.png',
    overlayIcon: '/assets.images/h5p-icons/drag-and-drop.png',
    description: 'Create drag and drop tasks with assets.images',
  },
  {
    text: 'Timeline',
    h5pLib: 'H5P.Timeline 1.1',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/timeline.png',
    overlayIcon: '/assets.images/h5p-icons/timeline.png',
    description: 'Create a timeline of events with multimedia',
  },
  {
    text: 'Accordion',
    h5pLib: 'H5P.Accordion 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/accordion.png',
    overlayIcon: '/assets.images/h5p-icons/accordion.png',
    description: 'Create vertically stacked expandable items',
  },

  {
    text: 'Advanced Fill The Blanks',
    h5pLib: 'H5P.AdvancedBlanks 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/advanced-fill-the-blanks.png',
    overlayIcon: '/assets.images/h5p-icons/advanced-fill-the-blanks.png',
    description: 'Create a Advanced Fill The Blanks',
  },
  {
    text: 'Agamotto',
    h5pLib: 'H5P.Agamotto 1.5',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/agamotto.png',
    overlayIcon: '/assets.images/h5p-icons/agamotto.png',
    description: 'Create a Agamotto',
  },
  {
    text: 'Arithmetic Quiz',
    h5pLib: 'H5P.ArithmeticQuiz 1.1',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/arithmetic-quiz.png',
    overlayIcon: '/assets.images/h5p-icons/arithmetic-quiz.png',
    description: 'Create a Arithmetic Quiz',
  },
  {
    text: 'Audio Recorder',
    h5pLib: 'H5P.AudioRecorder 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/audio-recorder.png',
    overlayIcon: '/assets.images/h5p-icons/audio-recorder.png',
    description: 'Create a Audio Recorder',
  },
  {
    text: 'Branching Scenario',
    h5pLib: 'H5P.BranchingScenario 1.1',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/branching-scenario.png',
    overlayIcon: '/assets.images/h5p-icons/branching-scenario.png',
    description: 'Create a Branching-Scenario',
  },
  {
    text: 'Chart',
    h5pLib: 'H5P.Chart 1.2',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/chart.png',
    overlayIcon: '/assets.images/h5p-icons/chart.png',
    description: 'Create a Chart',
  },
  {
    text: 'Collage',
    h5pLib: 'H5P.Collage 0.3',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/collage.png',
    overlayIcon: '/assets.images/h5p-icons/collage.png',
    description: 'Create a Collage',
  },
  {
    text: 'Column',
    h5pLib: 'H5P.Column 1.11',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/column.png',
    overlayIcon: '/assets.images/h5p-icons/column.png',
    description: 'Create a Column',
  },
  {
    text: 'Course Presentation',
    h5pLib: 'H5P.CoursePresentation 1.21',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/course-presentation.png',
    overlayIcon: '/assets.images/h5p-icons/course-presentation.png',
    description: 'Create a Course Presentation',
  },
  {
    text: 'Dialog Cards',
    h5pLib: 'H5P.DialogCards 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/dialog-cards.png',
    overlayIcon: '/assets.images/h5p-icons/dialog-cards.png',
    description: 'Create a Dialog Cards',
  },
  {
    text: 'Dictation',
    h5pLib: 'H5P.Dictation 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/dictation.png',
    overlayIcon: '/assets.images/h5p-icons/dictation.png',
    description: 'Create a Dictation',
  },
  {
    text: 'Documentation Tool',
    h5pLib: 'H5P.DocumentationTool 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/documentation-tool.png',
    overlayIcon: '/assets.images/h5p-icons/documentation-tool.png',
    description: 'Create a Documentation Tool',
  },
  {
    text: 'Drag The Words',
    h5pLib: 'H5P.DragText 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/drag-the-words.png',
    overlayIcon: '/assets.images/h5p-icons/drag-the-words.png',
    description: 'Create a Drag The Words',
  },
  {
    text: 'Essay',
    h5pLib: 'H5P.Essay 1.2',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/essay.png',
    overlayIcon: '/assets.images/h5p-icons/essay.png',
    description: 'Create a Essay',
  },
  {
    text: 'Fill In The Blanks',
    h5pLib: 'H5P.Blanks 1.12',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/fill-in-the-blanks.png',
    overlayIcon: '/assets.images/h5p-icons/fill-in-the-blanks.png',
    description: 'Create a Fill In The Blanks',
  },
  {
    text: 'Find Multiple Hotspots',
    h5pLib: 'H5P.ImageHotspotQuestion 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/find-multiple-hotspots.png',
    overlayIcon: '/assets.images/h5p-icons/find-multiple-hotspots.png',
    description: 'Create a Find Multiple Hotspots',
  },
  {
    text: 'Find The Words',
    h5pLib: 'H5P.FindTheWords 1.4',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/find-the-words.png',
    overlayIcon: '/assets.images/h5p-icons/find-the-words.png',
    description: 'Create a Find The Words',
  },
  {
    text: 'Guess The Answer',
    h5pLib: 'H5P.GuessTheAnswer 1.4',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/guess-the-answer.png',
    overlayIcon: '/assets.images/h5p-icons/guess-the-answer.png',
    description: 'Create a Guess The Answer',
  },
  {
    text: 'Iframe Embedder',
    h5pLib: 'H5P.IFrameEmbed 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/iframe-embedder.png',
    overlayIcon: '/assets.images/h5p-icons/iframe-embedder.png',
    description: 'Create a Iframe Embedder',
  },
  {
    text: 'Image Hotspot Question',
    h5pLib: 'H5P.ImageHotspotQuestion 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/image-hotspot-question.png',
    overlayIcon: '/assets.images/h5p-icons/image-hotspot-question.png',
    description: 'Create a Image Hotspot Question',
  },
  {
    text: 'Image Hotspots',
    h5pLib: 'H5P.ImageHotspots 1.8',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/image-hotspots.png',
    overlayIcon: '/assets.images/h5p-icons/image-hotspots.png',
    description: 'Create a Image Hotspots',
  },
  {
    text: 'Image Juxtaposition',
    h5pLib: 'H5P.ImageJuxtaposition 1.4',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/image-juxtaposition.png',
    overlayIcon: '/assets.images/h5p-icons/image-juxtaposition.png',
    description: 'Create a Image Juxtaposition',
  },
  {
    text: 'Image Pairing',
    h5pLib: 'H5P.ImagePair 1.4',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/image-pairing.png',
    overlayIcon: '/assets.images/h5p-icons/image-pairing.png',
    description: 'Create a Image Pairing',
  },
  {
    text: 'Image Slider',
    h5pLib: 'H5P.ImageSlider 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/image-slider.png',
    overlayIcon: '/assets.images/h5p-icons/image-slider.png',
    description: 'Create a Image Slider',
  },
  {
    text: 'Impressive Present',
    h5pLib: 'H5P.ImpressPresentation 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/impressive-present.png',
    overlayIcon: '/assets.images/h5p-icons/impressive-present.png',
    description: 'Create a Impressive-Present',
  },
  {
    text: 'Sequeincing',
    h5pLib: 'H5P.ImageSequencing 1.1',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/mage-sequeincing.png',
    overlayIcon: '/assets.images/h5p-icons/mage-sequeincing.png',
    description: 'Create a Mage Sequeincing',
  },
  {
    text: 'Mark The Words',
    h5pLib: 'H5P.MarkTheWords 1.9',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/mark-the-words.png',
    overlayIcon: '/assets.images/h5p-icons/mark-the-words.png',
    description: 'Create a Mark The Words',
  },
  {
    text: 'Memory Game',
    h5pLib: 'H5P.MemoryGame 1.3',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/memory-game.png',
    overlayIcon: '/assets.images/h5p-icons/memory-game.png',
    description: 'Create a Memory Game',
  },
  {
    text: 'Multiple Choice',
    h5pLib: 'H5P.MultiChoice 1.14',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/multiple-choice.png',
    overlayIcon: '/assets.images/h5p-icons/multiple-choice.png',
    description: 'Create a Multiple Choice',
  },
  {
    text: 'Personality Quiz',
    h5pLib: 'H5P.PersonalityQuiz 1.0',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/personality-quiz.png',
    overlayIcon: '/assets.images/h5p-icons/personality-quiz.png',
    description: 'Create a Personality Quiz',
  },
  {
    text: 'Questionnaire',
    h5pLib: 'H5P.Questionnaire 1.2',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/questionnaire.png',
    overlayIcon: '/assets.images/h5p-icons/questionnaire.png',
    description: 'Create a Questionnaire',
  },
  {
    text: 'QuestionSet',
    h5pLib: 'H5P.QuestionSet 1.17',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/quiz.png',
    overlayIcon: '/assets.images/h5p-icons/quiz.png',
    description: 'Create a Quiz',
  },
  {
    text: 'Single Choice Set',
    h5pLib: 'H5P.SingleChoiceSet 1.11',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/single-choice-set.png',
    overlayIcon: '/assets.images/h5p-icons/single-choice-set.png',
    description: 'Create a Single Choice Set',
  },
  {
    text: 'Speak the Words',
    h5pLib: 'H5P.SpeakTheWords 1.3',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/speak-the-words.png',
    overlayIcon: '/assets.images/h5p-icons/speak-the-words.png',
    description: 'Create a Speak The Words',
  },
  {
    text: 'Speak The Words Set',
    h5pLib: 'H5P.SpeakTheWords 1.3',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/speak-the-words-set.png',
    overlayIcon: '/assets.images/h5p-icons/speak-the-words-set.png',
    description: 'Create a Speak The Words Set',
  },
  {
    text: 'Summary',
    h5pLib: 'H5P.Summary 1.10',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/summary.png',
    overlayIcon: '/assets.images/h5p-icons/summary.png',
    description: 'Create a Summary',
  },
  {
    text: 'True False',
    h5pLib: 'H5P.TrueFalse 1.6',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/true-false.png',
    overlayIcon: '/assets.images/h5p-icons/true-false.png',
    description: 'Create a True False',
  },
  {
    text: 'Virtual Tour',
    h5pLib: 'H5P.ThreeImage 0.3',
    type: 'h5p',
    icon: '/assets.images/h5p-icons/virtual-tour.png',
    overlayIcon: '/assets.images/h5p-icons/virtual-tour.png',
    description: 'Create a Virtual Tour',
  },
];

export default h5pLibraries;
